### ISSUE TITLE
Couldn't connect to Twitter

### ISSUE THREAD

**Issue by AlexRowanCom** [Noleli/listcopy#6]
This is an excellent and useful app, which I have used over the years.

Today I saw this web page and message for the first time ever. (All was fine yesterday), after clicking the sign in with Twitter button.

http://projects.noahliebman.net/listcopy/redirect.php

_Could not connect to Twitter. Refresh the page or try again later._

I replicated the issue with a different Twitter account and different browser, thus ruling out those as being the cause.

I will try again tomorrow and if it doesn't work then, I will try yet another Twitter account and change my IP address.

**Comment by Noleli** [comment]
Sorry to hear it’s not working. It’s possible that the app hit Twitter’s API limits for the day, so hopefully it’ll be fine tomorrow.

**Comment by AlexRowanCom** [comment]
Thanks for your response Noleli. Yes, hopefully.

**Comment by apple56829** [comment]
I think this is why: https://twitter.com/TwitterAPI/status/1006635008692350977

**Comment by AlexRowanCom** [comment]
Thank you apple56829.

**Comment by Noleli** [comment]
Thanks, @apple56829! Fixed.
